### ISSUE TITLE
0.8.6 Compatability

### ISSUE THREAD

**Issue by VexWerewolf** [Ourobor/Hex-Size-Support#14]
Hex Size Support no longer appears to work properly with 0.8.6. Previously edited tokens retain their properties, offsets and sizes, but the icon for editing these does not appear when a token is selected.

**Comment by FolkvangrForgent** [comment]
I have already submitted a pull request of my fix for this issue #12 .

Assuming my fix is correct you can replace
`const configButton = html.find('.config');`
with
`const configButton = html.find('[data-action="config"]').first();`
in the modules/hex-size-support/modules/hooks.js (the code you need to change should be on line 11)

**Comment by Ourobor** [comment]
I apologize. I've been absolutely swamped with work this week, but I've been meaning to get time to look over the PR that should resolve this issue(as mentioned above, thanks @FolkvangrForgent). It's just a little difficult for me to check over it at the moment because my current version of foundry is still not updated and I'm running a mission in it and I don't want to mess it up. I'll try to dig up one of my old VMs and look it over some time tonight. Thanks for your patience!

**Comment by Ourobor** [comment]
This should now be resolved with the newest version available. Thank you for your patience.
