### ISSUE TITLE
Conflict with Show Drag Distance

### ISSUE THREAD

**Issue by intemptesta** [Ourobor/Hex-Size-Support#6]
Show Drag Distance Version 2.2.3
Hex Size Support Version 0.5.0
Foundry VTT 0.7.7
DnD5e 1.1.1
Happen on Firefox & Chrome

Show Drag Distance module conflict;
- Tokens with size 2 or more will offset slightly downward when dragged with mouse, move with arrow button not affected.
- Disabling Show Drag Distance stop this problem.

[I also submitted this problem to Show Drag Distance Dev.](https://github.com/wsaunders1014/ShowDragDistance/issues/84)
I'm willing to provide any additional info I can, hope I could help.

Edit: Sorry, I thought at first this module conflict with Token Mold module. Turn out it's Token Mold individual problem.

**Comment by Ourobor** [comment]
This is an issue with compatibility with the Show Drag Distance library and how it changes the way foundry moves tokens with drags. SDD overwrites the the way dragging works with its own implementation and because of this, none of the new code this module provides is used. I've been working on a patched version of the Show Drag Distance module and was going to talk with the dev once I had a solution, but I haven't been feeling well and haven't finished.

**Comment by intemptesta** [comment]
Thank you for your reply.
So this is a known issue, my worries' lifted.
Understood, please take time and hope you get well soon.

**Comment by akrigline** [comment]
Update here, since SDD is now no longer being maintained, Drag Ruler is being created as its successor:

https://foundryvtt.com/packages/drag-ruler/

https://github.com/manuelVo/foundryvtt-drag-ruler

As of the latest updates for both this module and Drag Ruler they are compatible. ❤️ teamwork!

**Comment by Ourobor** [comment]
True enough, closing the issue then as I don't plan on patching a dead module and as I understand it drag ruler is an accepted replacement which does have compatibility
