### ISSUE TITLE
[Question/Suggestion] Macro to change size.

### ISSUE THREAD

**Issue by intemptesta** [Ourobor/Hex-Size-Support#7]
Due to our group's love of using hex battle maps, this module really helps a lot.
But we switch the size of our tokens quite often, going through the menu is a little bit time-consuming.
Is there a way to change size in Hex Token Size Support with a macro?

**Comment by Ourobor** [comment]
You could if you wanted to, however I suspect that there's another issue here.
If you drag a token out into a scene, set up the token the way you want it to be, then reopen the actor, select the prototype token button and click assign token while that token is selected the token will maintain the settings each time it's brought out.

Here's a macro that seems to work, though I've only really tested it for a few minutes. I'll make a note to add a function to do this in the library itself so that all that would need to be called would be the function itself.

You only need to replace the value of newSize to make the macro do a different size. All sizes should be supported.
```js
//replace the 3 with whatever size you want, the rest should figure itself out
let newSize = 3;

let evenSnapping = true;

if(newSize % 2 != 0){
  evenSnapping = false
}

//we need to handle the race condition of setting two flags at the same time. The only way to deal with 
//this in a macro where await isn't available is to set a then callback and chain them this ugly way
token.setFlag('hex-size-support','borderSize',newSize.toString()).then(function(){
  token.setFlag('hex-size-support','evenSnap',evenSnapping)

  let updateData = {
    height: newSize.toString(),
    width: newSize.toString()
  }

  token.update(updateData).then(function() {
    token.data.width = Number(token.data.width);
    token.data.height = Number(token.data.height);
  });
})
```

**Comment by intemptesta** [comment]
This is it! Works beautifully for what I need, saving me multiple clicks and a lot more in the future.
Thank you for your help. I greatly appreciate it!
